export const USER_LOG_IN = "USER_LOG_IN";
export const USER_LOG_OUT = "USER_LOG_OUT";
export const USER_STATUS_UPDATE = "USER_STATUS_UPDATE";

export const SIGNUP_UPDATE_VALUES = "UDATE_SIGNUP_VALUES";
export const SIGNUP_SUBMIT_FORM = "SIGNUP_SUBMIT_FORM";
export const SIGNUP_SUBMIT_PIN = "SIGNUP_SUBMIT_PIN";
export const SIGNUP_END = "SIGNUP_END";
